Add HIP_CLANG_LAUNCHER for launching Clang through a wrapper executable
ROCm/llvm-project pull request #14
Opened 2024-01-20 16:01 UTC by GZGavinZhao

Fixes #147. Moved from ROCm/HIPCC#148.

This allows Clang to be called through a compiler wrapper/launcher. This is most commonly used to run clang through a compiler launcher that can cache compilations, such as ccache and sccache, to allow caching of compilation artifacts.

For a more detailed motivation and description, please see ROCm/ROCm#2817.

2024-01-20 18:09 UTC, kzhuravl commented
@david-salinas, please review this. Thanks!

2024-01-22 19:35 UTC, david-salinas requested changes
So this changes looks fine to me.  Though I do have two concerns.

1) We've changed the default for hipcc to use hipcc.bin instead of hipcc.pl, and this change is only in hipcc.pl.  I believe you just need a similar change here: https://github.com/ROCm/llvm-project/blob/a6ac1c71052a80cfcd75167a0e6acffeac5f3a09/amd/hipcc/src/hipBin_amd.h#L910

2) Windows.  We support hipcc, and ROCm on Windows.  Depending on the command used for HIP_CLANG_LAUNCHER, you may need to handle Windows file system paths with spaces, and general issues with the file system and executing commands in Windows and the need for double quotes.

2024-01-26 19:55 UTC, david-salinas approved these changes
OK Thanks for the change for hipcc.bin.  Looks good!

2024-06-14 20:54 UTC, closed without merging

2026-02-18 20:03 UTC, ScottTodd commented
This sort of change still looks useful, and there is code going to strange lengths to wrap executables with custom symlinks to implement reliable device kernel caching:
* https://github.com/ROCm/TheRock/pull/3482
* https://github.com/pytorch/pytorch/blob/32e8fbc95453330e6d51b9f195550518baaed992/.ci/docker/common/install_cache.sh#L110-L143

Should we pick up this work again, based on the more recent hipcc code?

2026-02-18 20:13 UTC, GZGavinZhao commented
@ScottTodd I'm open to merging this. I've been keeping this change rebased since at Solus we've been using this to cache HIP builds and it's been working well. Opened #1490.