ROCDOC-195
ROCm/llvm-project pull request #32
Opened 2024-02-09 12:29 UTC by MathiasMagnus

Related to: [SWDEV-427628 - Documentation restructure](https://github.com/ROCm/HIP/pull/3405)

2024-02-12 20:04 UTC, mjklemm approved these changes
I haven't checked all individual additions, but I have skimmed through several and it he ones I have checked look good.  So, LGTM.

2025-04-02 18:41 UTC, lamb-j commented
Do we still want these comments? Should we create an upstream PR for it?

2025-04-04 06:43 UTC, MathiasMagnus commented
@lamb-j I am no longer affiliated with AMD, so I can't give more info on that, nor do I see the SWDEV ticket I linked anymore. The intention was that the [math API reference page](https://rocm.docs.amd.com/projects/HIP/en/docs-6.3.3/reference/math_api.html) of the docs which is still [hardcoded](https://github.com/ROCm/hip/blob/amd-staging/docs/reference/math_api.rst) and gets out of date easily be taken from the headers themselves and be expanded via Sphinx Breathe. Whether that's still the direction, please contact the current doc team. Paging @neon60.

2025-04-04 16:31 UTC, lamb-j commented on clang/lib/Headers/__clang_hip_math.h
> +/// @brief Returns the maximum value of the input `double` arguments.
```suggestion
/// @brief Returns the minimum value of the input `double` arguments.
```

2025-04-04 16:31 UTC, lamb-j commented on clang/lib/Headers/__clang_hip_math.h
> +/// @brief Returns the minimum value of the input `float` arguments.
```suggestion
/// @brief Returns the maximum value of the input `float` arguments.
```

2025-04-04 16:46 UTC, searlmc1 requested changes
Is the intent to merge these changes into ROCm's llvm main branch - that branch should be a fast-forword merge of upstream's main branch.

2025-04-04 16:59 UTC, lamb-j commented
I'd support landing this upstream (not the ROCm main branch). I don't imagine there would be opposition to extra Doxygen comments, even if we're not planning to use Sphinx to auto-generate rocm.docs

With this upstream, we'd get more detailed descriptions here right? https://clang.llvm.org/doxygen/____clang__hip__math_8h.html

2026-06-22 19:50 UTC, closed without merging